In [1]:
import numpy as np

In [2]:
randomNumTable = np.random.randint(9, size=(500, 500))  # შემთხვევითი რიცხვების ცხრილი
print(randomNumTable)

[[0 2 4 ... 7 1 4]
 [3 7 1 ... 3 0 1]
 [4 6 2 ... 2 7 3]
 ...
 [4 0 4 ... 8 1 3]
 [1 8 8 ... 1 7 0]
 [5 2 4 ... 7 7 1]]


In [3]:
# გადავიყვანოთ ცხრილი ერთ განზომილებაში (შემდგომი ოპერაციების გამარტივებისთვის)
randomNumsList = ""
randomNumTable = randomNumTable.flatten()

for i in range(randomNumTable.size):
    randomNumsList += str(randomNumTable[i])

print(f"ცხრილი ერთ განზომილებაში არის {randomNumsList[:50]}...")

ცხრილი ერთ განზომილებაში არის 02450165265875880004315773111078320572532704111212...


#### a

ფირმის თანამშრომლებს ვნომრავთ 0-დან 99-მდე; <br>
შემთხვევითი რიცხვების ცხრილიდან ვარჩევთ სამნიშნა რიცხვებს და ვამატებთ შერჩეული რიცხვების სიაში, ისე რომ რიცხვები არ გავიმეოროთ;<br>
შერჩეული რიცხვების სიის მიხედვით ვირჩევთ თანამშრომლებს ნომრების მიხედვით

In [4]:
# შევარჩიოთ ორნიშნა რიცხვები სიიდან, მიყოლებით განსაზღვრული ადგილიდან (ჩვენს შემთხვევაში ვიწყებთ 0-დან)
# (მოცემული მაგალითსითვის შემთხვევითი რიცხვების რაოდენობა საკმარისია საჭიროების შემთხვევაში შესაძლებელია
# უფრო დიდი ცხრილის გამოყენება ან შერჩევის წესის შეცვლა)

def addToChosenNumbers(tableStartPos, randomNumsArray, chosenNumsLength):
    chosenNumbers = [] 
    
    randomNumsList = randomNumsArray 
    i = tableStartPos
    while (len(chosenNumbers) < chosenNumsLength):
        randomNum = int(randomNumsList[i: i+2])
        if randomNum not in chosenNumbers:
            chosenNumbers.append(randomNum)
        i += 2
        
    return chosenNumbers
        
    
chosenNumbers = addToChosenNumbers(0, randomNumsList, 30)

In [5]:
print("შეირჩევიან თანამშრომლები ნომრებით", chosenNumbers)

შეირჩევიან თანამშრომლები ნომრებით [2, 45, 1, 65, 26, 58, 75, 88, 0, 4, 31, 57, 73, 11, 10, 78, 32, 5, 72, 53, 27, 12, 30, 43, 80, 40, 47, 63, 16, 52]


#### b

In [6]:
# ავიღოთ მოცემული კლასტერიდან შემთხვევით შერჩეული სამი კლასტერი და შევკრიბოთ მათი მოცულობები
# (გავიმეოროთ ოპერაცია სამჯერ)

clusters = [15, 10, 20, 30, 5, 25, 35, 40, 5]

In [7]:
def randomClusters(clustersList):
    """ეს ფუნქცია ირჩევს სამ კლასტერს შემთხვევითი წესით და კრიბავს მათ მნიშვნელობებს"""
    
    clustersIndicies = []
    chosenClusters = []
    
    while (len(clustersIndicies) < 3):
        randomNum = np.random.randint(len(clustersList))
        if randomNum not in clustersIndicies:
            clustersIndicies.append(randomNum)
            chosenClusters.append(clustersList[randomNum])
            
    return clustersIndicies, sum(chosenClusters)

In [8]:
for i in range(3):
    chosenClusterIndicies, chosenClusterSum = randomClusters(clusters)
    print(f"შერჩეული კლასტერების ინდექსები - ცდა {i+1}: {chosenClusterIndicies}")
    print(f"შერჩეული კლასტერების ჯამი      - ცდა {i+1}: {chosenClusterSum}\n")

შერჩეული კლასტერების ინდექსები - ცდა 1: [1, 5, 0]
შერჩეული კლასტერების ჯამი      - ცდა 1: 50

შერჩეული კლასტერების ინდექსები - ცდა 2: [3, 8, 6]
შერჩეული კლასტერების ჯამი      - ცდა 2: 70

შერჩეული კლასტერების ინდექსები - ცდა 3: [8, 2, 4]
შერჩეული კლასტერების ჯამი      - ცდა 3: 30

